"""Removed description and added added_on column.

Revision ID: c2358ca30069
Revises: 0ad155cffa1d
Create Date: 2025-04-24 17:38:58.719317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2358ca30069'
down_revision: Union[str, None] = '0ad155cffa1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('added_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('books', 'added_on')
    # ### end Alembic commands ###
