"""Re-added the description column and added the is_read column.

Revision ID: ded6ff2a3d3a
Revises: a714d45ceb61
Create Date: 2025-04-27 12:21:25.525179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded6ff2a3d3a'
down_revision: Union[str, None] = 'a714d45ceb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_read')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
